In [1]:
import plotly.io as pio
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
dataset=pd.read_csv("Speed+Dating+Data.csv",encoding="latin1")
pd.options.display.max_columns=None
dataset.head(10)

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.00,20.00,20.00,20.00,0.00,5.00,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.00,0.00,0.00,40.00,0.00,0.00,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.00,18.00,19.00,18.00,14.00,12.00,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.00,5.00,15.00,40.00,5.00,5.00,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.00,10.00,20.00,10.00,10.00,20.00,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
5,1,1.0,0,1,1,1,10,7,NaN,6,6,16.0,0,0.25,0,25.0,2.0,50.00,0.00,30.00,10.00,0.00,10.00,1,7.0,7.0,8.0,8.0,7.0,7.0,7.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,0,4.0,9.0,7.0,4.0,6.0,4.0,6.0,5.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
6,1,1.0,0,1,1,1,10,7,NaN,1,7,17.0,0,0.34,0,30.0,2.0,35.00,15.00,25.00,10.00,5.00,10.00,0,3.0,6.0,7.0,5.0,8.0,7.0,2.0,1.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,7.0,4.0,6.0,7.0,6.0,5.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
7,1,1.0,0,1,1,1,10,7,NaN,2,8,18.0,0,0.50,0,27.0,2.0,33.33,11.11,11.11,11.11,11.11,22.22,0,6.0,7.0,5.0,6.0,8.0,6.0,7.0,5.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,0,4.0,9.0,7.0,6.0,5.0,6.0,6.0,7.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
8,1,1.0,0,1,1,1,10,7,NaN,8,9,19.0,1,0.28,0,28.0,2.0,50.00,0.00,25.00,10.00,0.00,15.00,1,7.0,7.0,8.0,8.0,8.0,9.0,6.5,8.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,9.0,8.0,8.0,7.0,7.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
9,1,1.0,0,1,1,1,10,7,NaN,9,10,20.0,0,-0.36,0,24.0,2.0,100.00,0.00,0.00,0.00,0.00,0.00,0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,6.0,8.0,10.0,8.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [3]:
dataset.shape

(8378, 195)

Suppression des colonnes inutiles

In [4]:
# Suppression des colonnes qui ne donnent pas d'informations supplémentaires

dataset=dataset.drop(['id','idg','condtn','round','position','positin1','order','partner','zipcode','length','numdat_2','attr7_2','sinc7_2','intel7_2','fun7_2','amb7_2','shar7_2','attr1_2','sinc1_2','intel1_2','fun1_2','amb1_2','shar1_2','attr4_2','sinc4_2','intel4_2','fun4_2','amb4_2','shar4_2','attr2_2','sinc2_2','intel2_2','fun2_2','amb2_2','shar2_2','attr3_2','sinc3_2','intel3_2','fun3_2','amb3_2','attr5_2','sinc5_2','intel5_2','fun5_2','amb5_2'],axis= 'columns')

# Suppression des colonnes avec beaucoup de valeurs manquantes

dataset=dataset.drop(['undergra','mn_sat','tuition','income','career_c'], axis="columns")
dataset=dataset.drop(['expnum','attr1_s','sinc1_s','intel1_s','fun1_s','amb1_s','shar1_s'], axis="columns")

# Analyses générales

## Quelles sont les attributs que préfèrent les personnes pour le sexe opposé ?

In [5]:
df_attr_sexe_oppose=dataset.loc[:,['gender','attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1','shar1_1']]

cols = ['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1','shar1_1']


rename_dict = {
    'attr1_1': 'Attractivité',
    'sinc1_1': 'Sincérité',
    'intel1_1': 'Intelligence',
    'fun1_1': 'Fun',
    'amb1_1': 'Ambition',
    'shar1_1': 'Interêts communs'
}

# Calcul des moyennes
df_attr_sexe_oppose[cols] /= 10   # on rapporte la note sur 10
df_h = df_attr_sexe_oppose[df_attr_sexe_oppose['gender'] == 0][cols].mean().rename(index=rename_dict)
df_f = df_attr_sexe_oppose[df_attr_sexe_oppose['gender'] == 1][cols].mean().rename(index=rename_dict)

# Subplots 1 ligne, 2 colonnes
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=("Attributs que préfèrent les femmes<br> chez les hommes", "Attributs que préfèrent les hommes<br> chez les femmes")
)

# Graphique gauche
fig.add_trace(
    go.Bar(x=df_h.index, y=df_h.values, name="Hommes"),
    row=1,
    col=1
)

# Graphique droite
fig.add_trace(
    go.Bar(x=df_f.index, y=df_f.values, name="Femmes"),
    row=1,
    col=2
)

fig.update_layout(
    title="Moyenne des points de préférence selon le sexe opposé",
    margin=dict(t=160),
    showlegend=False,
    width=800,
    height=450
)

fig.show()

Les femmes attribuent plus d'importance à l'intelligence pour les hommes, et les hommes attribuent plus d'importance à l'attractivité chez les femmes. L'ambition n'est pas forcément un point important chez les deux sexes.

##Est ce que ça a un réel impact dans le choix de revoir la personne ?

Est ce que la diminution des matchs n'est pas dûe à une mauvaise évaluation de ses propres préférences ?
On regarde pour chaque sexe la note moyenne donnée par le partenaire sur chaque attribut, uniquement quand le partenaire veut le/la revoir.

In [6]:
df_attr_sexe_oppose_real=dataset.loc[:,['gender','attr_o','sinc_o','intel_o','fun_o','amb_o','shar_o','dec_o']]
df_attr_sexe_oppose_real=df_attr_sexe_oppose_real[df_attr_sexe_oppose_real["dec_o"] == 1]
#quand le partenaire veut revoir la personne


cols = ['attr_o','sinc_o','intel_o','fun_o','amb_o','shar_o']  # ce sont les notes attribuées par le partenaire


rename_dict = {
    'attr_o': 'Attractivité',
    'sinc_o': 'Sincérité',
    'intel_o': 'Intelligence',
    'fun_o': 'Fun',
    'amb_o': 'Ambition',
    'shar_o': 'Interêts communs'
}


# Calcul des moyennes

df_eval_des_hommes = df_attr_sexe_oppose_real[df_attr_sexe_oppose_real['gender'] == 1][cols].mean().rename(index=rename_dict)
df_eval_des_femmes = df_attr_sexe_oppose_real[df_attr_sexe_oppose_real['gender'] == 0][cols].mean().rename(index=rename_dict)


# Subplots 1 ligne, 2 colonnes
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=("Notes moyennes quand les femmes <br> veulent revoir les hommes",
                    "Notes moyennes quand les hommes<br> veulent revoir les femmes")
)

# Graphique gauche
fig.add_trace(
    go.Bar(x=df_eval_des_hommes.index, y=df_eval_des_hommes.values, name="Hommes"),
    row=1,
    col=1
)

# Graphique droite
fig.add_trace(
    go.Bar(x=df_eval_des_femmes.index, y=df_eval_des_femmes.values, name="Femmes"),
    row=1,
    col=2
)

fig.update_layout(
    title="Notes moyennes attribuées par le partenaire quand il veut le/la revoir",
    margin=dict(t=160),
    showlegend=False,
    width=800,
    height=450
)

fig.show()

Les échelles ne sont pas les mêmes que pour les préférences, car ce ne sont plus des points distribués mais des notes pour chaque attribut.
On peut tout de même voir que les femmes choisissent effectivement des hommes qu'elles trouvent intelligents, mais que les hommes choisissent aussi selon ce critère.
Finalement, les personnes choisissent de manière générale des personnes à qui elles donnent des notes élevées sur à peu près tous les attributs.

C'est pourquoi on va s'intéresser aussi aux notes attribuées sur les personnes qu'on décide de ne pas revoir.

In [7]:
df_attr_sexe_oppose_dec0=dataset.loc[:,['gender','attr_o','sinc_o','intel_o','fun_o','amb_o','shar_o','dec_o']]
df_attr_sexe_oppose_dec0=df_attr_sexe_oppose_dec0[df_attr_sexe_oppose_dec0["dec_o"] == 0]
# quand le partenaire ne veut pas revoir la personne


cols = ['attr_o','sinc_o','intel_o','fun_o','amb_o','shar_o']  # ce sont les notes attribuées par le partenaire


rename_dict = {
    'attr_o': 'Attractivité',
    'sinc_o': 'Sincérité',
    'intel_o': 'Intelligence',
    'fun_o': 'Fun',
    'amb_o': 'Ambition',
    'shar_o': 'Interêts communs'
}


# Calcul des moyennes

df_eval_des_hommes = df_attr_sexe_oppose_dec0[df_attr_sexe_oppose_dec0['gender'] == 1][cols].mean().rename(index=rename_dict)
df_eval_des_femmes = df_attr_sexe_oppose_dec0[df_attr_sexe_oppose_dec0['gender'] == 0][cols].mean().rename(index=rename_dict)


# Subplots 1 ligne, 2 colonnes
fig = make_subplots(
    rows=1,
    cols=2,
    subplot_titles=("Notes moyennes quand les femmes <br> ne veulent pas revoir les hommes",
                    "Notes moyennes quand les hommes<br> ne veulent pas revoir les femmes")
)

# Graphique gauche
fig.add_trace(
    go.Bar(x=df_eval_des_hommes.index, y=df_eval_des_hommes.values, name="Hommes"),
    row=1,
    col=1
)

# Graphique droite
fig.add_trace(
    go.Bar(x=df_eval_des_femmes.index, y=df_eval_des_femmes.values, name="Femmes"),
    row=1,
    col=2
)

fig.update_layout(
    title="Notes moyennes attribuées par le partenaire quand il ne veut pas le/la revoir",
    margin=dict(t=160),
    showlegend=False,
    width=800,
    height=450
)

fig.show()

Cette fois, on observe plus de cohérence du côté des hommes : pour eux l'attractivité chez une femme est importante, et ils donnent une note plutôt basse à celles qu'ils ne veulent pas revoir.
Par contre, les femmes donnent des notes élevées d'intelligence aux hommes qu'elles ne veulent pas revoir, alors que c'était en moyenne leur critère de préférence.

Conclusion : les personnes de manière générale ont du mal à évaluer leurs préférences, ou cela est plus compliqué et dépend de plein d'autres paramètres.
Les personnes à qui on attribut des bonnes notes partout ont plus de chances d'avoir un match, mais cela ne fonctionne pas vraiment par critère.

(S'il y avait eu une corrélation entre les préférences par critère, et le choix par critère, on n'aurait pu s'intéresser à l'autoévaluation de chacun selon ces critères, mais ici ce n'est pas une analyse que je juge utile)

## Statistiques sur les personnes que le partenaire ne veut pas revoir, et celles que le partenaire veut revoir

In [8]:
dataset_a1=dataset[(dataset['dec_o']==0)]   # Les personnes qu'on ne veut pas revoir

dataset_a1.describe()

,iid,gender,wave,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,4863.000000,4863.000000,4863.000000,4853.000000,4863.0,4772.000000,4863.000000,4787.000000,4810.000000,4797.000000,4797.000000,4797.000000,4790.000000,4788.000000,4767.000000,4863.0,4662.000000,4614.000000,4601.000000,4572.000000,4388.000000,4137.000000,4630.000000,4588.000000,4558.000000,4816.000000,4821.000000,4836.000000,4828.000000,4828.000000,4828.000000,4821.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.00000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4828.000000,4815.000000,4828.000000,4828.000000,4828.000000,4825.000000,4818.000000,4801.000000,3780.000000,3780.000000,3780.000000,3780.000000,3780.000000,3763.000000,4828.000000,4828.000000,4828.000000,4828.000000,4825.000000,4825.000000,4817.000000,4817.000000,4817.000000,4817.000000,4817.000000,2884.000000,2884.000000,2884.000000,2884.000000,2884.000000,4863.000000,4694.000000,4635.000000,4628.000000,4588.000000,4366.000000,4151.000000,4667.000000,4631.000000,4602.000000,4222.000000,2281.000000,2281.000000,2281.000000,2281.000000,2281.000000,4328.000000,2258.000000,2258.000000,2258.000000,740.000000,353.000000,2258.000000,2258.000000,2258.000000,2258.000000,2258.000000,2258.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1669.000000,1136.000000,2258.000000,2258.000000,2258.000000,2258.000000,2258.000000,1136.000000,1136.000000,1136.000000,1136.000000,1136.000000
mean,285.791281,0.548016,11.406128,284.591799,0.0,0.191106,0.385976,26.318989,2.699792,22.719585,17.223187,20.308405,17.477574,10.801495,11.614342,0.0,5.367224,6.858257,7.077483,5.697835,6.494758,4.719604,5.312894,4.633500,1.972137,26.503738,7.595727,2.828577,3.793911,3.665286,2.139188,5.086704,2.259735,6.298882,4.626346,6.076636,7.692005,6.950083,6.666943,5.670878,3.98488,5.624482,7.681649,5.380075,6.793289,7.950704,6.826015,7.825601,5.522991,4.275891,5.592523,22.125195,17.808995,20.241874,17.242027,10.491976,12.271927,26.125661,11.415344,12.669048,15.696561,9.583598,11.201701,29.433629,13.672539,14.600008,18.401367,11.967107,12.008622,6.977164,8.297280,7.588333,8.432219,7.559892,6.861650,7.929265,8.325243,7.346394,7.603675,0.439646,6.289391,7.052643,7.258535,6.326177,6.678195,5.365695,6.072145,4.930900,0.938722,3.202274,7.102806,8.070583,8.258878,7.538799,7.570364,5.815850,0.756422,0.742250,0.320195,1.087838,0.875354,23.646802,17.072414,19.597493,16.104402,10.848308,12.948875,30.082746,16.250000,16.572183,16.472711,8.112676,12.615317,24.727981,11.103655,11.517675,14.403835,9.291791,11.342121,24.202516,11.222289,11.870581,14.889754,9.715398,12.406690,7.139504,8.125332,8.365810,7.521258,7.300266,6.657570,7.636444,7.924296,7.031690,7.053697
std,159.088721,0.497740,6.036685,160.072661,0.0,0.304695,0.486875,3.409811,1.180216,12.528762,7.046926,6.797452,5.956407,6.131879,6.080233,0.0,1.820690,1.830878,1.638937,1.955774,1.881180,2.072970,1.751788,2.118131,0.196224,3.744818,3.724013,1.255300,2.804372,2.802715,1.397004,1.431112,1.164908,2.618230,2.840849,2.419606,1.796056,2.065178,2.256884,2.570168,2.64226,2.488681,2.054856,2.510866,2.187962,1.650801,2.150147,1.800327,2.600873,2.731872,1.724751,11.707299,7.076318,6.728823,6.035490,6.030573,6.494340,15.982007,6.888557,6.926465,7.340632,6.739640,6.231105,15.987278,7.170423,6.309430,6.481339,6.856789,6.236005,1.449273,1.409824,1.621637,1.086588,1.816257,1.564854,1.676754,1.275577,1.825832,1.784622,0.496395,1.891352,1.719368,1.550909,1.890975,1.760380,2.099505,1.808822,2.061652,0.999970,2.448506,1.469073,1.427047,1.200216,1.688560,1.793868,1.814244,1.582754,1.111823,0.466655,0.985202,0.743371,12.932859,7.077319,6.095906,5.058390,5.672662,6.764636,17.060871,9.158372,7.721934,7.042299,6.138747,8.922421,16.820154,5.883005,6.102970,6.835854,6.249072,6.794061,16.922548,6.434904,6.649050,7.759643,6.197287,7.213308,1.640625,1.637175,1.493723,1.776312,2.000490,1.617033,1.507938,1.385733,1.752747,1.794196
min,1.000000,0.000000,1.000000,1.000000,0.0,-0.730000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,4.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,158.000000,0.000000,7.000000,154.000000,0.0,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.310000,15.000000,5.000000,10.000000,0.0,4.000000,6.000000,6.000000,5.000000,5.000000,3.000000,4.000000,3.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,4.000000,2.000000,4.000000,7.000000,6.000000,5.000000,3.000000,2.00000,4.000000,7.000000,4.000000,5.000000,7.000000,5.000000,7.000000,3.000000,2.000000,5.000000,15.000000,15.000000,17.390000,15.000000,5.000000,10.000000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,8.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,6.000000,7.000000,8.000000,7.000000,7.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,15.220000,15.000000,16.670000,15.000000,7.000000,10.000000,20.000000,10.000000,10.000000,10.000000,3.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,9.000000,7.000000,7.000000,9.000000,7.000000,10.000000,6.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,285.000000,1.000000,11.000000,279.000000,0.0,0.210000,0.000000,26.000000,2.000000,20.000000,18.000000,20.000000,18.000000,10.000000,10.000000,0.0,5.000000,7.000000,7.000000,6.000000,7.000000,5.000000,5.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.00000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,20.000000,19.050000,20.000000,17.780000,10.000000,11.900000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,6.000000,7.000000,5.000000,6.000000,5.000000,0.000000,3.000000,7.000000,8.000000,8.000000,8.000000,8.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,20.000000,17.190000,20.000000,16.000000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,15.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,409.000000,1.000000,15.000000,409.000000,0.0,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.000000,20.000000,15.000000,15.090000,0.0,7.000000,8.000000,8.000000,7.000000,8.000000,6.000000,6.875000,6.000000,2.000000,29.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,8.000000,7.000000,8.000000,9.000000,8.000000,8.000000,8.000000,6.00000,8.000000,9.000000,7.000000,8.000000,9.000000,8.000000,9.000000,8.000000,6.000000,7.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.670000,30.000000,15.000000,18.000000,20.000000,14.250000,15.000000,35.000000,20.000000,20.000000,20.000000,15.380000,16.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,6.000000,2.000000,4.000000,8.000000,9.000000,9.000000,9.000000,9.000000,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,30.000000,15.000000,15.000000,20.000000,10.000000,15.000000,30.000000,15.000000,15.000000,20.000000,10.000000,17.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,1.000000,21.000000,552.000000,0.0,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,0.0,10.000000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,7.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.00000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [9]:
dataset_a2=dataset[(dataset['dec_o']==1)]  # Les personnes qu'on veut revoir

dataset_a2.describe()

,iid,gender,wave,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,3515.000000,3515.000000,3515.000000,3515.000000,3515.000000,3448.000000,3515.000000,3487.000000,3495.000000,3492.000000,3492.000000,3492.000000,3490.000000,3483.000000,3482.000000,3515.0,3504.000000,3477.000000,3471.000000,3446.000000,3268.000000,3165.000000,3498.000000,3472.000000,3435.000000,3467.000000,3475.000000,3479.000000,3471.000000,3471.000000,3471.000000,3460.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3471.000000,3462.000000,3471.000000,3471.000000,3471.000000,3464.000000,3461.000000,3456.000000,2709.000000,2709.000000,2709.000000,2709.000000,2709.000000,2704.000000,3471.000000,3471.000000,3471.000000,3471.000000,3464.000000,3464.000000,3456.000000,3456.000000,3456.000000,3456.000000,3456.000000,2022.00000,2022.000000,2022.000000,2022.000000,2022.000000,3515.000000,3482.000000,3466.000000,3454.000000,3440.000000,3300.000000,3160.000000,3471.000000,3438.000000,3401.000000,2983.000000,1719.000000,1719.000000,1719.000000,1719.000000,1719.000000,3135.000000,1716.000000,1716.000000,1716.000000,756.000000,315.000000,1716.000000,1716.000000,1716.000000,1716.000000,1716.000000,1716.000000,880.000000,880.000000,880.000000,880.000000,880.000000,880.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.00000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,1290.000000,880.000000,1716.000000,1716.000000,1716.000000,1716.000000,1716.000000,880.000000,880.000000,880.000000,880.000000,880.000000
mean,280.749360,0.434993,11.274538,282.858606,0.392603,0.202796,0.409388,26.428162,2.834907,22.187308,17.635452,20.219044,17.435201,10.525748,12.162984,1.0,7.285645,7.595916,7.756122,7.332995,7.159272,6.462085,7.221984,5.967742,1.944396,26.157773,7.755108,2.657948,3.772112,3.632671,2.098243,4.895376,2.016710,6.600980,4.504754,6.481129,7.911553,7.035436,6.780755,5.829156,3.736963,5.915010,7.674157,5.198502,6.752233,7.876404,6.824546,7.886488,5.781907,4.427254,5.452917,23.056321,16.822472,20.298632,17.756539,10.947819,11.252187,26.769288,10.591731,12.590624,15.385751,10.054264,10.754808,31.653780,12.718911,14.162184,18.452181,11.434428,11.640583,7.234664,8.291667,7.866319,8.364583,7.604167,7.05638,7.924332,8.226014,7.540059,7.637488,0.392603,6.056002,7.339008,7.516068,6.499855,6.908939,5.617563,6.217373,5.580134,0.962364,3.215655,7.355148,8.097150,8.256254,7.896451,7.614311,5.567464,0.812937,1.296620,0.451632,1.370370,1.000000,25.355256,15.951935,19.166404,16.403176,10.963561,12.370530,32.940909,14.885227,16.818182,16.347727,7.451136,11.681818,26.751938,10.295349,11.534109,14.112403,9.09845,11.139535,25.965116,10.536434,12.058915,15.048837,9.281395,11.397727,7.372960,8.051282,8.418998,7.839744,7.511655,7.006818,7.587500,7.943182,7.314773,7.042045
std,157.857406,0.495827,5.939030,156.524705,0.488399,0.301845,0.491791,3.764197,1.293033,12.621262,7.034004,6.763479,6.259183,6.116483,6.718268,0.0,1.534084,1.513961,1.329753,1.511844,1.592697,1.841109,1.319101,1.893360,0.298696,3.293522,3.805452,1.189246,2.902585,2.809035,1.421074,1.455927,0.999572,2.610352,2.745584,2.398397,1.687882,2.033342,2.271116,2.567795,2.583412,2.511525,1.937680,2.550935,2.299287,1.767622,2.165098,1.779589,2.612975,2.695571,1.743923,13.701961,6.965779,6.858489,6.142204,6.245015,6.125593,16.722481,6.295307,6.415483,7.308457,7.336777,5.805022,16.524131,6.659527,6.190477,6.710799,6.916807,6.064737,1.303084,1.404355,1.465695,1.061444,1.723969,1.39121,1.553821,1.293173,1.704297,1.756768,0.488399,2.019304,1.754867,1.537763,2.030392,1.829658,2.221088,1.881101,2.162827,0.976064,2.439966,1.327802,1.493248,1.151344,1.517758,1.792379,1.820212,1.648916,1.619851,0.497800,1.526063,0.761326,14.621827,7.917744,6.155132,5.295954,6.189036,6.260206,18.047937,9.511230,8.081982,7.471721,6.033835,8.178533,18.235479,5.519306,5.876344,7.044395,6.55942,6.138743,17.072461,5.925631,7.453789,8.159576,6.654435,6.704794,1.478181,1.573744,1.412097,1.685633,1.902701,1.327901,1.500573,1.281335,1.550004,1.615287
min,1.000000,0.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.00000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,5.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,151.000000,0.000000,7.000000,156.000000,0.000000,-0.010000,0.000000,24.000000,2.000000,15.000000,15.000000,17.780000,15.000000,5.000000,8.000000,1.0,6.000000,7.000000,7.000000,6.000000,6.000000,5.000000,6.000000,5.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,5.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,1.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,15.000000,13.460000,17.390000,15.000000,5.000000,7.000000,10.000000,6.000000,8.000000,9.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,5.000000,10.000000,7.000000,8.000000,7.000000,8.000000,7.000000,6.00000,7.000000,8.000000,7.000000,7.000000,0.000000,5.000000,6.000000,7.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,7.000000,7.000000,8.000000,7.000000,7.000000,4.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.280000,13.950000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,8.000000,5.00000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,7.000000,7.000000,6.750000,6.000000
50%,272.000000,0.000000,11.000000,282.000000,0.000000,0.220000,0.000000,26.000000,2.000000,20.000000,19.000000,20.000000,18.000000,10.000000,11.540000,1.0,7.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,6.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,7.000000,4.000000,7.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,5.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,5.000000,20.000000,18.000000,20.000000,18.750000,10.000000,10.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,30.000000,13.040000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.00000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,8.000000,8.000000,7.000000,7.000000,6.000000,6.000000,6.000000,1.000000,3.000000,8.000000,8.000000,8.000000,8.000000,8.000000,6.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.000000,20.000000,17.020000,10.000000,13.950000,30.000000,15.000000,15.000000,15.000000,7.000000,10.000000,21.000000,10.000000,10.000000,10.000000,9.00000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,406.500000,1.000000,15.000000,406.000000,1.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,25.000000,20.000000,15.000000,17.000000,1.0,8.000000,9.000000,9.000000,8.000000,8.000000,8.000000,8.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,5.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,25.000000,20.000000,23.000000,20.000000,15.000000,15.000000,35.000000,15.000000,15.000000,20.000000,15.000000,15.000000,40.000000,17.140000,19.540000,20.000000,15.000000,15.220000,8.000000,9.000000,9.000000,9.000000,9.000000,8.00000,9.000000,9.000000,9.000000,9.000000,1.000000,7.000000,8.000000,9.000000,8.000000,8.000000,7.000000,8.000000,7.000000,2.000000,5.000000,8.000000,9.000000,9.000000,9.000000,9.000000,7.000000,1.000000,2.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.305000,16.670000,45.000000,20.000000,20.000000,20.000000,10.000000,20.000000,40.000000,15.000000,15.000000,20.000000,10.00000,15.000000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,1.000000,21.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.0,10.500000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,7.000000,18.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.00000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

En observant les différentes moyennes et médianes, il y a en moyenne un peu plus d'hommes qui veulent revoir des femmes que l'inverse.
Et comme vu précédemment, les personnes qu'on a envie de revoir ont des notes plus élevées sur tous les critères que les personnes qu'on n'a pas envie de revoir.

## Observation du nombre de matchs par objectif de la soirée

In [10]:

df_goal=dataset.groupby("goal")["match"].sum().reset_index()

df_goal["goal"] = df_goal["goal"].replace({
    1.0: "Pour la soirée",
    2.0: "Rencontrer de nouvelles personnes",
    3.0: "Avoir un rendez vous",
    4.0: "Pour une relation sérieuse",
    5.0: "Pour pouvoir dire que je l’ai fait",
    6.0: "Autre"
})

fig=px.pie(df_goal,names="goal",values="match",title="Proportion du nombre de match pour chaque objectif")
fig.show()

On voit que ce sont surtout les personnes qui n'ont pas d'attentes particulières sur la soirée et qui ne veulent pas forcément une relation sérieuse qui matchent. Les personnent qui ont plus d'attentes précises matchent moins.

## Observation du nombre de matchs par fréquence accordée aux dates

In [11]:
df_date=dataset.groupby("date")["match"].sum().reset_index()

df_date["date"] = df_date["date"].replace({
    1.0: "Plusieurs fois par semaine",
    2.0: "Deux fois par semaine",
    3.0: "Une fois par semaine",
    4.0: "Deux fois par mois",
    5.0: "Une fois par mois",
    6.0: "Plusieurs fois dans l'année",
    7.0: "Presque jamais"
})

fig=px.pie(df_date,names="date",values="match",title="Proportion du nombre de match par fréquence accordée aux dates")
fig.show()

Ceux qui matchent accordent tout de même du temps aux dates, mais pas trop régulièrement.
Le temps accordé aux dates n'est pas très révélateur des matchs.

## Division en trois groupes, pour étudier chaque rendez vous

J'aimerai m'intéresser plus particulièrement à chaque rendez vous, selon s'ils veulent se revoir ou pas.
Je place donc chaque personne et son partenaire dans un des trois groupes suivants:

*   Premier groupe Groupe_0_0 :les deux personnes du rendez vous ne veulent pas se revoir; il n'y a pas match.

*  Second groupe Groupe_0_1 : il n'y a qu'une personne sur les deux qui veut revoir l'autre; il n'y a pas match.

*  Troisième groupe Groupe_1_1: les deux personnes veulent se revoir; il y a match.

In [12]:
dataset.shape

(8378, 138)

In [13]:
dataset = dataset.dropna(subset=['pid'])
dataset['pid']=dataset['pid'].astype(int)


dataset_q1=pd.DataFrame()
dataset_q2=pd.DataFrame()
dataset_q3=pd.DataFrame()

for i in range (len(dataset)):
  iid_i=dataset.iloc[i]['iid']
  pid_i=dataset.iloc[i]['pid']
  ligne_i=dataset.iloc[[i]]
  row_pid = dataset[(dataset['iid'] == pid_i) & (dataset['pid']==iid_i)]
  if (row_pid.iloc[0]['dec_o']==0) and (ligne_i.iloc[0]['dec_o']==0):
    dataset_q1=pd.concat([dataset_q1,ligne_i,row_pid],ignore_index=True)
  elif (row_pid.iloc[0]['dec_o']==1) and (ligne_i.iloc[0]['dec_o']==1):
    dataset_q3=pd.concat([dataset_q3,ligne_i,row_pid],ignore_index=True)
  else:
    dataset_q2=pd.concat([dataset_q2,ligne_i,row_pid],ignore_index=True)

dataset_q1 = dataset_q1.drop_duplicates()
dataset_q2 = dataset_q2.drop_duplicates()
dataset_q3 = dataset_q3.drop_duplicates()

Je m'intéresse à la colonne int_corr, qui indique l'indice de corrélation entre les centres d'interêts

In [14]:
df_corr_q1=dataset_q1['int_corr']
df_corr_q1 = df_corr_q1.iloc[::2].reset_index(drop=True) ## on supprime les corrélations doublées du partenaire
df_corr_q1 = df_corr_q1[df_corr_q1 >= 0]

df_corr_q2=dataset_q2['int_corr']
df_corr_q2 = df_corr_q2.iloc[::2].reset_index(drop=True)
df_corr_q2 = df_corr_q2[df_corr_q2 >= 0]

df_corr_q3=dataset_q3['int_corr']
df_corr_q3 = df_corr_q3.iloc[::2].reset_index(drop=True)
df_corr_q3 = df_corr_q3[df_corr_q3 >= 0]

df_box = pd.DataFrame({
    'corr': pd.concat([df_corr_q1, df_corr_q2, df_corr_q3]),
    'groupe': (
        ['Groupe_0_0'] * len(df_corr_q1) +
        ['Groupe_0_1'] * len(df_corr_q2) +
        ['Groupe_1_1'] * len(df_corr_q3)
    )
})

fig = px.box(
    df_box,
    x='groupe',
    y='corr',
    color='groupe',
    title="Distribution des corrélations d'intérêts par groupe"
)

fig.update_layout(
    xaxis_title="Groupes",
    yaxis_title="Corrélation d'intérêts"
)

fig.show()

Dans les trois groupes, on voit que la distribution de la corrélation des interêts est la même. On peut dire que ça n'a pas d'incidence.

## Activités et centres d'interêts communs au sein de chaque groupe

On s'intéresse maintenant tout de même aux réponses fournies dans le questionnaire sur les différents centres d'interêts et activités, et si cela a une influence selon les groupes.

In [15]:
df_q1_pairs=dataset_q1.iloc[::2].reset_index(drop=True)      # On découpe en dataset pair et impair,
df_q1_impairs=dataset_q1.iloc[1::2].reset_index(drop=True)   # pour avoir chaque ligne des deux sous datasets qui
                                                             # correspondent à une personne du même rendez vous
df_q2_pairs=dataset_q2.iloc[::2].reset_index(drop=True)
df_q2_impairs=dataset_q2.iloc[1::2].reset_index(drop=True)

df_q3_pairs=dataset_q3.iloc[::2].reset_index(drop=True)
df_q3_impairs=dataset_q3.iloc[1::2].reset_index(drop=True)


## Je définis une fonction qui va compter pour chaque rendez vous une somme:
## +1 si la différence des notes attribuées de chaque partenaire pour le centre d'interêts est inférieure ou égale à 3
## 0 sinon, je stocke chaque somme de chaque rendez vous dans une liste

colonnes_interets = [
    'sports', 'tvsports', 'exercise', 'dining',
    'museums', 'art', 'hiking', 'gaming',
    'clubbing', 'reading', 'tv', 'theater',
    'movies', 'concerts', 'music', 'shopping', 'yoga'
]

def calcul_interets_communs(df_pairs, df_impairs):
    count_interest = []
    for i in range(len(df_pairs)):
        count = 0
        for col in colonnes_interets:
            if abs(df_pairs.loc[i, col] - df_impairs.loc[i, col]) <= 2:
                    count=count+1

        count_interest.append(count)

    # je ramène à un score sur 10 car il y a 17 centres d'interêts
    count_interest_sur10 = [(x / 17) * 10 for x in count_interest]

    return count_interest_sur10


q1_score = calcul_interets_communs(df_q1_pairs, df_q1_impairs)
q2_score = calcul_interets_communs(df_q2_pairs, df_q2_impairs)
q3_score = calcul_interets_communs(df_q3_pairs, df_q3_impairs)

In [16]:
# Je stocke dans un dataframe pour comparer les statistiques

df_interest = pd.DataFrame({
    "groupe": (
        ["Groupe_0_0"] * len(q1_score) +
        ["Groupe_0_1"] * len(q2_score) +
        ["Groupe_1_1"] * len(q3_score)
    ),
    "valeur": q1_score + q2_score + q3_score
})

fig = px.box(
    df_interest,
    x="groupe",
    y="valeur",
    color="groupe",
    title="Distribution des centres d’intérêt en communs pour chaque groupe"
)

fig.update_traces(boxmean=True)

fig.update_layout(
    xaxis_title="Groupes",
    yaxis_title="Score sur 10"
)

fig.show()

On peut voir que la distribution est sensiblement la même dans les trois groupes, et que la médiane du groupe des matchs est un peu plus élevée, donc que les personnes ont un peu plus de centres d'interêts en communs. Ce n'est pas significatif non plus, on ne peut pas conclure que les centres d'interêts ont une influence dans les matchs.

## Observation des différences d'âge selon le groupe

In [17]:
# On observe la différence d'âge entre chaque partenaire

diff_age_q1 = abs(df_q1_pairs.iloc[:, 7] - df_q1_impairs.iloc[:, 7])
diff_age_q2 = abs(df_q2_pairs.iloc[:, 7] - df_q2_impairs.iloc[:, 7])
diff_age_q3 = abs(df_q3_pairs.iloc[:, 7] - df_q3_impairs.iloc[:, 7])



df_age_mean = pd.DataFrame({
    "groupe": ["Groupe_0_0", "Groupe_0_1", "Groupe_1_1"],
    "moyenne_diff_age": [
        diff_age_q1.mean(),
        diff_age_q2.mean(),
        diff_age_q3.mean()
    ]
})

import plotly.express as px

fig = px.bar(
    df_age_mean,
    x="groupe",
    y="moyenne_diff_age",
    text="moyenne_diff_age",
    title="Moyenne des différences d'âge selon le groupe"
)

fig.update_layout(
    xaxis_title="Groupes",
    yaxis_title="Moyenne des différences d'âge"
)

fig.show()

Dans le groupe où il y a les matchs, les personnes ont en moyenne un peu plus le même âge que sur les deux autres groupes.

## Observation des études selon le groupe

In [18]:
def calc_etudes(df_pairs, df_impairs):
    count = 0

    for i in range(len(df_pairs)):
        if df_pairs.iloc[i, 26] == df_impairs.iloc[i, 26]:
            count = count+1

    total = len(df_pairs)
    different = total - count

    return count, different

q1_same, q1_diff = calc_etudes(df_q1_pairs, df_q1_impairs)
q2_same, q2_diff = calc_etudes(df_q2_pairs, df_q2_impairs)
q3_same, q3_diff = calc_etudes(df_q3_pairs, df_q3_impairs)

df_all = pd.DataFrame({
    "groupe": ["Groupe_0_0", "Groupe_0_1", "Groupe_1_1"],
    "même études": [q1_same, q2_same, q3_same],
    "différentes": [q1_diff, q2_diff, q3_diff]
})


fig = make_subplots(
    rows=1, cols=3,
    specs=[[{"type": "domain"}, {"type": "domain"}, {"type": "domain"}]],
    subplot_titles=["Groupe_0_0", "Groupe_0_1", "Groupe_1_1"]
)

fig.add_trace(go.Pie(
    labels=["Même études", "Études différentes"],
    values=[q1_same, q1_diff],
    name="Groupe_0_0"
), 1, 1)

fig.add_trace(go.Pie(
    labels=["Même études", "Études différentes"],
    values=[q2_same, q2_diff],
    name="Groupe_0_1"
), 1, 2)

fig.add_trace(go.Pie(
    labels=["Même études", "Études différentes"],
    values=[q3_same, q3_diff],
    name="Groupe_1_1"
), 1, 3)

fig.update_layout(title_text="Comparaison des études entre partenaires")

fig.show()

On peut observer qu'il y a un peu plus de personnes qui font les mêmes études dans le groupe des matchs, mais ce n'est pas un critère qui permet de tirer une conclusion sur les matchs, et que la plupart des personnes font des études différentes.

## Conclusion

On observe, concernant les matchs, que les personnes attribuant des notes élevées sur l'ensemble des critères veulent revoir le partenaire de manière générale, mais l'attractivité est tout de même importante pour les deux sexes : les personnes qui ne donnent pas une bonne note sur l'attractivité ne veulent en général pas revoir la personne, même si elles ont attribué des bonnes notes sur les autres critères.
Les personnes qui matchent, ont aussi en général un peu plus le même âge, n'ont pas forcément d'attentes sur l'objectif du rendez vous, et accordent des rendez vous de temps en temps.
Les interêts communs ou les études n'ont pas d'incidence sur les matchs.